# This is template workflow which is responsible for syncronization between repository default branch and 
# Bioconductor devel branch. It's triggered by gDE bioc packages on every pull request merge, then it merge
# default branch to bioc devel branch and push changes to bioc remote.

name: bioc-sync

on:
  pull_request:
    types: [closed]
  workflow_call:
    inputs:
      PACKAGE_NAME:
        required: true
        type: string
      DEFAULT_BRANCH:
        required: true
        type: string
    secrets:
      BIOC_SSH_KEY:
        required: true

jobs:
  bioc-sync:
    if: github.event.pull_request.merged
    runs-on: ubuntu-20.04
    steps:
      - name: config ssh
        env:
          BIOC_SSH_KEY: ${{ secrets.BIOC_SSH_KEY }}
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir ~/.ssh
          ssh-keyscan git.bioconductor.org >> ~/.ssh/known_hosts
          echo "$BIOC_SSH_KEY" >> ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null 
          ssh-add ~/.ssh/id_rsa

      - name: checkout repo
        uses: actions/checkout@v4

      - name: bioc sync
        env:
          PACKAGE_NAME: ${{ github.event.repository.name }}
          DEFAULT_BRANCH: main
        run: |
          git config --local user.email "gdr-support-d@gene.com"
          git config --local user.name "gDR team"
          git remote add upstream git@git.bioconductor.org:packages/${{ env.PACKAGE_NAME }}.git
          git fetch upstream devel
          git checkout devel
          git merge ${{ env.DEFAULT_BRANCH }}
          git push upstream devel
        shell: bash {0}
