name: bioc-sync

on:
  pull_request:
    types: [closed]
  push:
    branches:
      - 'GDR-2318'

jobs:
  bioc-sync:
#    if: github.event.pull_request.merged
    runs-on: ubuntu-20.04
    env:
      BIOC_SSH_KEY: ${{ secrets.BIOC_SSH_KEY }}
    steps:
      #- name: config ssh
      #  uses: webfactory/ssh-agent@v0.8.0
      #  with:
      #    ssh-private-key: ${{ secrets.BIOC_SSH_KEY }}
      - name: checkout repo
        uses: actions/checkout@v4

      - name: bioc sync
        run: |
          mkdir ~/.ssh
          echo $BIOC_SSH_KEY >> ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          cat ~/.ssh/id_rsa
          
          git config --local user.email "gdr-support-d@gene.com"
          git config --local user.name "gDR team"
          git remote add upstream git@git.bioconductor.org:packages/gDRstyle.git
          git fetch upstream devel
          git checkout devel
          git merge master
          git push upstream devel
        shell: bash {0}
